// Kali Teeri Wrapped 2025 Data
const wrappedData = [
  {
    type: "intro",
    title: "2025",
    subtitle: "Kali Teeri Wrapped",
    theme: "theme-intro",
  },
  {
    type: "ranked_list",
    title: "The Boldest Bidders",
    items: [
      { label: "Reena", value: "211.1 pts" },
      { label: "Rajen", value: "203.6 pts" },
      { label: "Samir", value: "201.3 pts" },
      { label: "Jesal", value: "198.1 pts" },
      { label: "Yogesh", value: "198.0 pts" },
      { label: "Pinkey", value: "196.2 pts" },
      { label: "Mital", value: "194.6 pts" },
      { label: "Hiral", value: "194.3 pts" },
      { label: "Paresh", value: "189.6 pts" },
      { label: "Apurv", value: "189.5 pts" },
    ],
    theme: "theme-2",
  },
  {
    type: "ranked_list",
    title: "The Champions (Overall Win %)",
    items: [
      { label: "Jesal", value: "66.4%" },
      { label: "Apurv", value: "66.4%" },
      { label: "Samir", value: "65.8%" },
      { label: "Reena", value: "61.5%" },
      { label: "Pinkey", value: "61.4%" },
      { label: "Rajen", value: "61.1%" },
      { label: "Paresh", value: "60.9%" },
      { label: "Yogesh", value: "60.1%" },
      { label: "Hiral", value: "59.5%" },
      { label: "Mital", value: "57.1%" },
    ],
    theme: "theme-4",
  },
  {
    type: "big_highlight",
    title: "Clutch King",
    name: "Yogesh",
    stat: "15 Wins ≥ 220 pts",
    description: "The master of the high-stakes game.",
    theme: "theme-5",
  },
  {
    type: "big_highlight",
    title: "The Most Wanted",
    name: "Hiral & Pinkey",
    stat: "125 Times Called",
    // New data structure for the Podium layout
    extraPlayers: [
      { name: "Reena", stat: "116" },
      { name: "Rajen", stat: "107" },
    ],
    description: "The most sought-after teammates of 2025.",
    theme: "theme-3",
  },
  {
    type: "ranked_list",
    title: "The Kingmakers (Teammate Win %)",
    items: [
      { label: "Yogesh", value: "67.8%" },
      { label: "Jesal", value: "65.4%" },
      { label: "Apurv", value: "65.2%" },
      { label: "Hiral", value: "64.0%" },
      { label: "Reena", value: "63.8%" },
      { label: "Pinkey", value: "63.2%" },
      { label: "Paresh", value: "59.8%" },
      { label: "Samir", value: "58.8%" },
      { label: "Mital", value: "55.7%" },
      { label: "Rajen", value: "55.1%" },
    ],
    theme: "theme-1",
  },
  {
    type: "ranked_list",
    title: "Individual Nemesis",
    items: [
      { label: "Paresh ↔ Yogesh", value: "23 losses" },
      { label: "Pinkey ↔ Yogesh", value: "23 losses" },
      { label: "Rajen ↔ Yogesh", value: "22 losses" },
      { label: "Samir ↔ Yogesh", value: "22 losses" },
      { label: "Hiral ↔ Yogesh", value: "17 losses" },
      { label: "Mital ↔ Yogesh", value: "17 losses" },
      { label: "Jesal ↔ Yogesh", value: "13 losses" },
      { label: "Apurv ↔ Yogesh", value: "12 losses" },
      { label: "Reena ↔ Yogesh", value: "12 losses" },
    ],
    theme: "theme-3",
  },
  {
    type: "big_highlight",
    title: "Unstoppable Trio",
    name: "Hiral, Pinkey & Yogesh",
    stat: "7 Wins Together",
    description: "The dream team that dominated the deck.",
    theme: "theme-4",
  },
  {
    type: "intro",
    title: "Game Over",
    subtitle: "See you in 2026! 🃏",
    theme: "theme-intro",
  },
];
