// Kali Teeri Wrapped 2025 Data
const wrappedData = [
  {
    type: "intro",
    title: "2025",
    subtitle: "Kali Teeri Wrapped",
    theme: "theme-intro",
  },
  {
    type: "ranked_list",
    title: "The Workhorses",
    description: "Total rounds played across all games",
    items: [
      { label: "Yogesh", value: "253 rounds" },
      { label: "Pinkey", value: "176 rounds" },
      { label: "Paresh", value: "169 rounds" },
      { label: "Hiral", value: "163 rounds" },
      { label: "Rajen", value: "157 rounds" },
      { label: "Samir", value: "155 rounds" },
      { label: "Reena", value: "148 rounds" },
      { label: "Mital", value: "147 rounds" },
      { label: "Apurv", value: "125 rounds" },
      { label: "Jesal", value: "116 rounds" },
    ],
    theme: "theme-1",
  },
  {
    type: "ranked_list",
    title: "The Commanders",
    description:
      "Percentage of rounds as leader (total leader rounds in brackets)",
    items: [
      { label: "Yogesh", value: "65.6% (166)" },
      { label: "Paresh", value: "39.6% (67)" },
      { label: "Samir", value: "37.4% (58)" },
      { label: "Rajen", value: "31.8% (50)" },
      { label: "Jesal", value: "30.2% (35)" },
      { label: "Pinkey", value: "29.0% (51)" },
      { label: "Mital", value: "27.9% (41)" },
      { label: "Apurv", value: "26.4% (33)" },
      { label: "Hiral", value: "23.3% (38)" },
      { label: "Reena", value: "21.6% (32)" },
    ],
    theme: "theme-2",
  },
  {
    type: "ranked_list",
    title: "The Bold Bidders",
    description: "Average points bid when leading",
    items: [
      { label: "Reena", value: "211.1 pts" },
      { label: "Rajen", value: "203.6 pts" },
      { label: "Samir", value: "201.3 pts" },
      { label: "Jesal", value: "198.1 pts" },
      { label: "Yogesh", value: "198.0 pts" },
      { label: "Pinkey", value: "196.2 pts" },
      { label: "Mital", value: "194.6 pts" },
      { label: "Hiral", value: "194.3 pts" },
      { label: "Paresh", value: "189.6 pts" },
      { label: "Apurv", value: "189.5 pts" },
    ],
    theme: "theme-3",
  },
  {
    type: "ranked_list",
    title: "The Fearless Risk Takers",
    description:
      "Percentage of leadership rounds with bids ≥200 points (rounds in brackets)",
    items: [
      { label: "Reena", value: "53.1% (17)" },
      { label: "Samir", value: "32.8% (19)" },
      { label: "Rajen", value: "32.0% (16)" },
      { label: "Yogesh", value: "30.7% (51)" },
      { label: "Jesal", value: "28.6% (10)" },
      { label: "Hiral", value: "26.3% (10)" },
      { label: "Mital", value: "24.4% (10)" },
      { label: "Pinkey", value: "21.6% (11)" },
      { label: "Paresh", value: "20.9% (14)" },
      { label: "Apurv", value: "6.1% (2)" },
    ],
    theme: "theme-5",
  },
  {
    type: "ranked_list",
    title: "The Podium Regulars",
    description: "Total games finishing in top 3 positions",
    items: [
      { label: "Yogesh", value: "34 finishes" },
      { label: "Samir", value: "28 finishes" },
      { label: "Pinkey", value: "27 finishes" },
      { label: "Paresh", value: "26 finishes" },
      { label: "Apurv", value: "25 finishes" },
      { label: "Rajen", value: "18 finishes" },
      { label: "Jesal", value: "17 finishes" },
      { label: "Hiral", value: "16 finishes" },
      { label: "Reena", value: "13 finishes" },
      { label: "Mital", value: "13 finishes" },
    ],
    theme: "theme-2",
  },
  {
    type: "ranked_list",
    title: "The Preferred Partners",
    description: "Most frequent teammates when leading",
    items: [
      { label: "Yogesh", value: "Reena (5.5%), Mital (5.5%), Hiral (5.1%)" },
      { label: "Pinkey", value: "Reena (10.8%), Hiral (10.2%), Rajen (9.7%)" },
      { label: "Apurv", value: "Reena (12.8%), Pinkey (12.0%), Jesal (11.2%)" },
      { label: "Jesal", value: "Apurv (12.1%), Mital (11.2%), Samir (10.3%)" },
      { label: "Paresh", value: "Pinkey (8.9%), Mital (7.7%), Reena (7.1%)" },
      { label: "Hiral", value: "Pinkey (11.0%), Rajen (9.8%), Samir (9.2%)" },
      { label: "Samir", value: "Hiral (9.7%), Rajen (9.0%), Reena (8.4%)" },
      { label: "Mital", value: "Yogesh (9.5%), Jesal (8.8%), Rajen (8.8%)" },
      { label: "Rajen", value: "Pinkey (10.8%), Hiral (10.2%), Reena (9.6%)" },
      { label: "Reena", value: "Pinkey (12.8%), Apurv (10.8%), Rajen (10.1%)" },
    ],
    theme: "theme-4",
  },
  {
    type: "intro",
    title: "Game Over",
    subtitle: "See you in 2026! 🃏",
    theme: "theme-intro",
  },
];
